export const FETCH_USER = "fetch_user";
export const FETCH_ARTICLE_DETAIL = "FETCH_ARTICLE_DETAIL";
export const FETCH_MY_ARTICLES = "FETCH_MY_ARTICLES";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
